CREATE TABLE IF NOT EXISTS product (
  id VARCHAR(32) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  sku VARCHAR(64) NULL,
  type ENUM('GOOD','SERVICE') NOT NULL,
  unit ENUM('KG','HOUR','PIECE') NOT NULL,
  isWeightable TINYINT(1) NOT NULL DEFAULT 0,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  taxCode VARCHAR(32) NULL,
  groupId VARCHAR(64) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS price (
  id VARCHAR(32) PRIMARY KEY,
  productId VARCHAR(32) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
  validFrom DATETIME NOT NULL,
  validTo DATETIME NULL,
  FOREIGN KEY (productId) REFERENCES product(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customer (
  id VARCHAR(32) PRIMARY KEY,
  fullName VARCHAR(255) NOT NULL,
  phone VARCHAR(32) UNIQUE NOT NULL,
  email VARCHAR(255) NULL,
  birthday DATE NULL,
  notes TEXT NULL,
  createdAt DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `order` (
  id VARCHAR(32) PRIMARY KEY,
  number VARCHAR(64) UNIQUE NOT NULL,
  customerId VARCHAR(32) NULL,
  cashierId VARCHAR(32) NOT NULL,
  shiftId VARCHAR(32) NULL,
  status ENUM('DRAFT','PAID','REFUNDED','CANCELLED') NOT NULL,
  createdAt DATETIME NOT NULL,
  paidAt DATETIME NULL,
  grandTotal DECIMAL(10,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (customerId) REFERENCES customer(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_item (
  id VARCHAR(32) PRIMARY KEY,
  orderId VARCHAR(32) NOT NULL,
  productId VARCHAR(32) NOT NULL,
  qty INT NOT NULL DEFAULT 1,
  weightKg DECIMAL(10,3) NULL,
  unitPrice DECIMAL(10,2) NOT NULL,
  discountAbs DECIMAL(10,2) NULL,
  discountPct DECIMAL(5,2) NULL,
  total DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (orderId) REFERENCES `order`(id) ON DELETE CASCADE,
  FOREIGN KEY (productId) REFERENCES product(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment (
  id VARCHAR(32) PRIMARY KEY,
  orderId VARCHAR(32) NOT NULL,
  method ENUM('CASH','CARD','ONLINE','MIXED','LOYALTY') NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (orderId) REFERENCES `order`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pond_resource (
  id VARCHAR(32) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  capacity INT NOT NULL,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  locationNote VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reservation (
  id VARCHAR(32) PRIMARY KEY,
  resourceId VARCHAR(32) NOT NULL,
  customerId VARCHAR(32) NOT NULL,
  status ENUM('HELD','PAID','CANCELLED','NOSHOW') NOT NULL,
  startAt DATETIME NOT NULL,
  endAt DATETIME NOT NULL,
  prepayAmount DECIMAL(10,2) NULL,
  notes TEXT NULL,
  FOREIGN KEY (resourceId) REFERENCES pond_resource(id) ON DELETE RESTRICT,
  FOREIGN KEY (customerId) REFERENCES customer(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;